var FANCYTREE_ITEMS = {
		TRAWL : {key: "3", title:"Trawl Survey",
		         CATCH : {key: "4", title:"Catch", url:"trawl.catch_fact"},
			     HAUL_CHARS : {key: "5", title:"Haul Characteristics", url:"trawl.operation_haul_fact"},
			     SPECIMENS : {key: "6", title:"Specimens", url: "trawl.individual_fact"},
			     STATION_GRID : {key: "7", title:"Station Grid", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/WCGBTS_SamplingGrid_blk/MapServer',mapServices: []}}	,
		HOOK_LINE : {key: "8", title:"Hook & Line Survey",
			        SPECIMENS : {key: "10", title:"Specimens", url: "hooknline.individual_hooknline_view"},
					CATCH : {key: "9", title:"Catch (by Site)", url: "hooknline.catch_hooknline_view"},
					SAMPLING_SITES: {key: "11", title:"Sampling Sites", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/HookAndLine_SamplingSites/MapServer',mapServices: []}}	,
		OBSERVER : {key: "1", title:"Observer Program",
						 FISHING_EFFORT_2002_2015 : {key: "40", title:"Fishing Effort",
											  AT_SEA_MID_TRAWL_CP_2002_2005 : {key: "41", title:"At-Sea Midwater Trawl CP (2002-2005)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2002 – 2005)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_ASHOP_CP_Period1/MapServer',mapServices: []},
											  AT_SEA_MID_TRAWL_CP_2006_2010 : {key: "42", title:"At-Sea Midwater Trawl CP (2006-2010)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2006 – 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_ASHOP_CP_Period2/MapServer',mapServices: []},
											  AT_SEA_MID_TRAWL_CP_2011_2015 : {key: "43", title:"At-Sea Midwater Trawl CP (2011-2015)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_ASHOP_CP_Period3/MapServer',mapServices: []},
											  AT_SEA_MID_TRAWL_MS_2002_2005 : {key: "44", title:"At-Sea Midwater Trawl MS (2002-2005)", tooltip:"At-Sea Midwater Trawl Mothership (2002 – 2005)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_ASHOP_Mother_Period1/MapServer',mapServices: []},
											  AT_SEA_MID_TRAWL_MS_2006_2010 : {key: "45", title:"At-Sea Midwater Trawl MS (2006-2010)", tooltip:"At-Sea Midwater Trawl Mothership (2006 – 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_ASHOP_Mother_Period2/MapServer',mapServices: []},
											  AT_SEA_MID_TRAWL_MS_2011_2015 : {key: "46", title:"At-Sea Midwater Trawl MS (2011-2015)", tooltip:"At-Sea Midwater Trawl Mothership (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_ASHOP_Mother_Period3/MapServer',mapServices: []},
											  LE_BOTTOM_TRAWL_2002_2006 : {key: "47", title:"LE Bottom Trawl (2002-mid-2006)", tooltip:"Limited-Entry Bottom Trawl (2002 – mid-2006)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_BotTWL_Period1/MapServer',mapServices: []},
											  LE_BOTTOM_TRAWL_2006_2010 : {key: "48", title:"LE Bottom Trawl (mid-2006-2010)", tooltip:"Limited-Entry Bottom Trawl (mid-2006 – 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_BotTWL_Period2/MapServer',mapServices: []},
											  CS_BOTTOM_TRAWL_2002_2010 : {key: "49", title:"CS Bottom Trawl (2011-2015)", tooltip:"Catch Shares Bottom Trawl (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_BotTWL_Period3/MapServer',mapServices: []},
											  NON_CS_HOOK_LINE_2002_2010 : {key: "50", title:"Non-CS Hook & Line (2002-2010)", tooltip:"Non-Catch Shares Hook-and-Line (2002 – 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_NonCS_HL_Period1_2/MapServer',mapServices: []},
											  NON_CS_HOOK_LINE_2011_2015 : {key: "51", title:"Non-CS Hook & Line (2011-2015)", tooltip:"Non-Catch Shares Hook-and-Line (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_NonCS_HL_Period3/MapServer',mapServices: []},
											  CS_HOOK_LINE_2011_2015 : {key: "52", title:"CS Hook & Line (2011-2015)", tooltip:"Catch Shares Hook-and-Line (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_CS_HL_Period3/MapServer',mapServices: []},
											  NON_CS_POT_2002_2010 : {key: "53", title:"Non-CS Pot (2002-2010)", tooltip:"Non-Catch Shares Pot (2002 – 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_NonCS_Pot_Period1_2/MapServer',mapServices: []},
											  NON_CS_POT_2011_2015 : {key: "54", title:"Non-CS Pot (2011-2015)", tooltip:"Non-Catch Shares Pot (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_NonCS_Pot_Period3/MapServer',mapServices: []},
											  CS_POT_2011_2015 : {key: "55", title:"CS Pot (2011-2015)", tooltip:"Catch Shares Pot (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_CS_Pot_Period3/MapServer',mapServices: []},
											  SHORESIDE_MID_TRAWL_HAKE_2011_2015 : {key: "56", title:"Shoreside Midwater Trawl Hake (2011-2015)", tooltip:"Shoreside Midwater Trawl for Hake (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_Shoreside_Hake/MapServer',mapServices: []},
											  SHORESIDE_MID_TRAWL_ROCKFISH_2011_2015 : {key: "57", title:"Shoreside Midwater Trawl Rockfish (2011-2015)", tooltip:"Shoreside Midwater Trawl for Rockfish (2011 – 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_Shoreside_RF/MapServer',mapServices: []}},

						 CATCH_EXPANSIONS: {key: "2", title:"Catch Expansions", url:"observer.catch_observer_view"},
						 GEMM: {key: "58", title:"GEMM", url:"observer.gemm_fact"}},
		EFH : {key: "39", title:"Groundfish Essential Fish Habitat (EFH)",
						HABITAT_MAP : {key: "23", title:"Habitat Map",
											  OSU_ATSML_3_6_1 : {key: "26", title:"OSU ATSML v3.6.1 (Coast-wide)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/Habitat_OSU_ATSML_v3_6_1_IND/MapServer',mapServices: []},
											  OSU_ATSML_3_6_1_4_0 : {key: "88", title:"OSU ATSML v4.0/3.6.1 (Coast-wide)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Habitat_Induration_v4_v361/MapServer',mapServices: []},
											  OSU_ATSML_4_0 : {key: "27", title:"OSU ATSML v4.0", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/Habitat_OSU_ATSML_v4_0_IND/MapServer',mapServices: []}},
						GENERAL : {key: "59", title:"General",
                                              GROUNDFISH_TRAWL_RCA_POLY_2015_2016 : {key: "65", title:"Groundfish Trawl RCA Polygons (2017 - 2019)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/RCA_CommTrawl_2017_19_poly/MapServer',mapServices: []},
                                              GROUNDFISH_TRAWL_RCA_LINES_2015_2016 : {key: "66", title:"Groundfish Trawl RCA Lines (2015 - 2016)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/RCA_CommTrawl_2015_16_line/MapServer',mapServices: []},
											  ECONOMIC_EXCLUSION_ZONE : {key: "69", title:"Economic Exclusion Zone (EEZ)", url : 'https://maritimeboundaries.noaa.gov/arcgis/rest/services/MaritimeBoundaries/US_Maritime_Limits_Boundaries/MapServer',mapServices: [3]},
											  MARINE_PROTECTED_AREAS : {key: "70", title:"Marine Protected Areas", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/MPA_Inventory_2017_FishRestr/MapServer',mapServices: []},
											  PFMC_LANDMARKS : {key: "67", title:"PFMC EFH Landmarks", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Landmarks/MapServer',mapServices: []},
											  STATE_TERRIT_SEA_BOUND : {key: "60", title:"State Territorial Sea Boundary", url : 'https://gis.boem.gov/arcgis/rest/services/BOEM_BSEE/MMC_Layers/MapServer',mapServices: [8]},
											  TRIBAL_USUAL_ACCUSTOMED_AREAS : {key: "68", title:"Tribal Usual & Accustomed Areas", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/REG_Tribal_UA_poly/MapServer',mapServices: []}
								  },
						AMENDMENT_19 : {key: "77", title:"Amendment 19",
											  EFH : {key: "78", title:"EFH",
											            EFH_700_BOTTOM_TRAWL : {key: "79", title:"EFH 700 ftm bottom trawl closure", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd19_EFHCA_700ftm/MapServer',mapServices: []},
											            EFH_CONSERVATION_AREAS : {key: "80", title:"EFH Conservation Areas", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd19_EFHCA/MapServer',mapServices: []},
											            EFH_DESIGNATED_AREAS : {key: "81", title:"EFH Designated Area", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd19_DesigArea/MapServer',mapServices: []}
											         }
								  },
						AMENDMENT_28 : {key: "61", title:"Amendment 28",
											  EFH : {key: "62", title:"EFH",
											            ALT_1 : {key: "63", title:"Alternative 1: No Action", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1_NoAction/MapServer',mapServices: []},
											            ALT_1A : {key: "90", title:"Alternative 1a: Collaborative", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1a_Collaborative/MapServer',mapServices: []},
											            ALT_1B : {key: "91", title:"Alternative 1b: Oceana", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1b_Oceana/MapServer',mapServices: []},
											            ALT_1C : {key: "92", title:"Alternative 1c: MTC", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1c_MTC/MapServer',mapServices: []},
											            ALT_1D : {key: "93", title:"Alternative 1d: Garibaldi Reef South", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1d_GaribaldiReefSo/MapServer',mapServices: []},
											            ALT_1E : {key: "94", title:"Alternative 1e: Rittenburg Bank", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1e_RittenburgBank/MapServer',mapServices: []},
											            ALT_1F : {key: "95", title:"Alternative 1f: Potato Bank", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1f_PotatoBank/MapServer',mapServices: []},
											            ALT_1G : {key: "108", title:"Alternative 1g: Priority Habitats", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1g_PriorityHabitats/MapServer',mapServices: []},
											            ALT_1H : {key: "110", title:"Alternative 1h: PFMC FPA", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt1h_PFMC_FPA/MapServer',mapServices: []},
												  		ALT_3 : {key: "96", title:"Alternative 3: Habitats >3500m", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt3_DeeperThan3500m/MapServer',mapServices: []}
											         },
											  RCA : {key: "64", title:"RCA",
											            ALT_2 : {key: "97", title:"Alternative 2: No Action", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt2_RCA_NoAction/MapServer',mapServices: []},
											            ALT_2A : {key: "98", title:"Alternative 2a: Remove RCA", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt2a_RemoveRCA/MapServer',mapServices: []},
											            ALT_2B : {key: "99", title:"Alternative 2b: Discrete Area Closures", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt2b_DiscreteAreaClosures/MapServer',mapServices: []},
											            ALT_2C : {key: "100", title:"Alternative 2c: Block Area Closures", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Amd28_Alt2c_BlockAreaClosures/MapServer',mapServices: []}
											         }
								  },
						FISHING_EFFORT : {key: "82", title:"Fishing Effort",
			                        CS_BOTTOM_TRAWL_2011_2015 : {key: "83", title:"CS Bottom Trawl (2011-2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_BotTWL_Period3/MapServer',mapServices: []},
			                        NON_CS_HOOK_LINE_2011_2015 : {key: "84", title:"Non-CS Hook and Line (2011-2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_NonCS_HL_Period3/MapServer',mapServices: []},
			                        CS_HOOK_LINE_2011_2015 : {key: "85", title:"CS Hook and Line (2011-2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_IFQ_HL_Period3/MapServer',mapServices: []},
			                        NON_CS_POT_2011_2015 : {key: "86", title:"Non-CS Pot (2011-2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_NonIFQ_Pot_Period3/MapServer',mapServices: []},
			                        CS_POT_2011_2015 : {key: "87", title:"CS Pot (2011-2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/FishingEffort_2002_2015_IFQ_Pot_Period3/MapServer',mapServices: []},
			                        BOTTOM_TRAWL_2011_2015 : {key: "101", title:"Bottom Trawl (2011 - 2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_BottomTrawl_Period3/MapServer',mapServices: []},
			                        BOTTOM_TRAWL_2006_2010 : {key: "102", title:"Bottom Trawl (Jun 2006 - 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_BottomTrawl_Period2/MapServer',mapServices: []},
			                        BOTTOM_TRAWL_2002_2006 : {key: "103", title:"Bottom Trawl (2002 - Jun 2006)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_BottomTrawl_Period1/MapServer',mapServices: []},
			                        FIXED_GEAR_2006_2010 : {key: "104", title:"Fixed Gear (Jun 2006 - 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_FixedGear_Period2/MapServer',mapServices: []},
			                        FIXED_GEAR_2002_2006 : {key: "105", title:"Fixed Gear (2002 - Jun 2006)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_FixedGear_Period1/MapServer',mapServices: []},
			                        MID_TRAWL_2006_2010 : {key: "106", title:"Midwater Trawl (Jun 2006 - 2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_MidwaterTrawl_Period2/MapServer',mapServices: []},
			                        MID_TRAWL_2002_2006 : {key: "107", title:"Midwater Trawl (2002 - Jun 2006)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_FE_MidwaterTrawl_Period1/MapServer',mapServices: []}
							 },
						SPECIES_DISTRIBUTION : {key: "109", title:"Species Distribution",
			                         CORAL_SPONGE_OBS : {key: "71", title:"Coral and Sponge Observations", url : 'https://tiles.arcgis.com/tiles/C8EMgrsFcRFL6LrL/arcgis/rest/services/DSCRTP_Web_Mercator/MapServer',mapServices: []},
			                          SPONGE_BYCATCH : {key: "74", title:"Sponge Bycatch", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Bycatch_Sponges/MapServer',mapServices: []},
                                      SPONGE_PRESENCE : {key: "89", title:"Sponge Presence (1 x 1 km)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Presence_Sponges/MapServer',mapServices: []},
                                      SEA_PEN_WHIP_BYCATCH : {key: "75", title:"Sea Pen / Sea Whip Bycatch", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Bycatch_Pennatulids/MapServer',mapServices: []},
                                      SEA_PEN_WHIP_PRES : {key: "76", title:"Sea Pen / Sea Whip Presence (1 x 1 km)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Presence_Pennatulids/MapServer',mapServices: []},
                                      CORAL_SPONGE_PRESENCE : {key: "72", title:"Coral Presence (1 x 1 km)", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Presence_Corals/MapServer',mapServices: []},
									 CORAL_BYCATCH : {key: "73", title:"Coral Bycatch", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/EFH_Bycatch_Corals/MapServer',mapServices: []}


							 }
				},
		SPATIAL_REFERENCES : {key: "12", title:"Spatial References",
					
			        BATHYMETRIC_CONTOURS : {key: "13", title:"Bathymetric Contours", url : 'https://gis.ngdc.noaa.gov/arcgis/rest/services/web_mercator/gebco_2014_contours/MapServer',mapServices: []},
			       
					MARINE_PROTECTED_AREAS : {key: "14", title:"Marine Protected Areas", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/MPA_Inventory_2017_FishRestr/MapServer',mapServices: []},
					NMFS_TRAWL_RCA : {key: "38", title:"NMFS Trawl Rockfish Conservation<br>Area (RCA), 2015-16", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/RCA_CommTrawl_2015_16_poly/MapServer',mapServices: []},
					REGULATORY_BOUNDARIES : {key: "15", title:"Regulatory Boundaries",
											  PFMC_LANDMARKS : {key: "21", title:"PFMC Landmarks", url:'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/REG_PFMC_Landmarks/MapServer',mapServices: []},
											  INPFC_AREAS : {key: "22", title:"INPFC Areas", url:'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/REG_INPFC_Areas/MapServer',mapServices: []}}}	,
			CATCH : {key: "16", title:"Catch",
						NASC_2012 : {key: "32", title:"Acoustics / Hake Survey NASC<BR>Hake Biomass 2012"},
						NASC_2013 : {key: "33", title:"Acoustics / Hake Survey NASC<BR>Hake Biomass 2013"},
						NASC_2015 : {key: "34", title:"Acoustics / Hake Survey NASC<BR>Hake Biomass 2015"}},
		ACOUSTICS_HAKE_SURVEY : {key: "17", title:"Acoustics / Hake Survey",
			        NASC_2012 : {key: "18", title:"NASC 2012", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/Acoustics_Survey2012/MapServer',mapServices: []},
					NASC_2013 : {key: "30", title:"NASC 2013", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/Acoustics_Survey2013/MapServer',mapServices: []},
					NASC_2015 : {key: "31", title:"NASC 2015", url : 'https://www.webapps.nwfsc.noaa.gov/server/rest/services/FRAM/Acoustics_Survey2015/MapServer',mapServices: []},
			        SONAR_DATA : {key: "28", title:"Sonar Data", url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/water_column_sonar/MapServer',mapServices: [] },
			        VESSEL_TRANSECTS : {key: "29", title:"Vessel Transects", url:'https://maps.ngdc.noaa.gov/arcgis/rest/services/water_column_sonar/MapServer',mapServices: []}},
			SPECIMENS : {key: "19", title:"Specimens"},
			SAMPLING_STATIONS_GRIDS : {key: "20", title:"Sampling Stations/Grids",
						VESSEL_TRANSECTS : {key: "35", title:"Acoustics / Hake Survey<BR>Vessel Transects"}},
			SONAR_DATA: {key: "36", title:"Sonar Data",
						ACOUSTICS_HAKE_SURVEY : {key: "37", title:"Acoustics / Hake Survey"}},
			OPERATION_CHARS : {key: "24", title:"Operation Characteristics",
			TRAWL_SURVEY_HAULS: {key: "25", title:"Trawl Survey Hauls"}}
			

};