var FANCYTREE_ITEMS = {
	TRAWL : {key: "1", title:"Trawl Survey",
			CATCH : {key: "2", title:"Catch", url:"trawl.catch_fact"},
			SPECIMENS : {key: "3", title:"Specimens", url: "trawl.individual_fact"},
			HAUL_CHARS : {key: "4", title:"Haul Characteristics", url:"trawl.operation_haul_fact"},				
			STATION_GRID : {key: "5", title:"Station Grid", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/WCGBTS_SamplingGrid_map/MapServer',mapServices: []}
			},
	HOOK_LINE : {key: "6", title:"Hook & Line Survey",
			CATCH : {key: "7", title:"Catch (by Site)", url: "hooknline.catch_hooknline_view"},				
			SPECIMENS : {key: "8", title:"Specimens", url: "hooknline.individual_hooknline_view"},
			SAMPLING_SITES: {key: "9", title:"Sampling Sites", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/SoCalHookandLineSurvey/FeatureServer',mapServices: [0]}
			},
	ACOUSTICS_HAKE_SURVEY : {key: "10", title:"Acoustics / Hake Survey",
			NASC_2012 : {key: "11", title:"NASC 2012", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/Pacific_Hake_Adult_Relative_Adundance/FeatureServer',mapServices: [2]},
			NASC_2013 : {key: "12", title:"NASC 2013", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/Pacific_Hake_Adult_Relative_Adundance/FeatureServer',mapServices: [1]},
			NASC_2015 : {key: "13", title:"NASC 2015", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/Pacific_Hake_Adult_Relative_Adundance/FeatureServer',mapServices: [0]},
			SONAR_DATA : {key: "14", title:"Sonar Data (through 2015)", url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/water_column_sonar/MapServer',mapServices: [0,1,2,3,4,5,6]}
			},
	OBSERVER : {key: "15", title:"Observer Program",
			CATCH_EXPANSIONS: {key: "16", title:"Catch Expansions", url:"observer.catch_observer_view"},
			GEMM: {key: "17", title:"GEMM", url:"observer.gemm_fact"},
			FISHING_EFFORT_2002_2017 : {key: "18", title:"Fishing Effort",
					LE_BOTTOM_TRAWL_2002_2006 : {key: "19", title:"LE Bottom Trawl (2002-mid-2006)", tooltip:"Limited-Entry Bottom Trawl (2002–mid-2006)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [0]},
					LE_BOTTOM_TRAWL_2006_2010 : {key: "20", title:"LE Bottom Trawl (mid-2006-2010)", tooltip:"Limited-Entry Bottom Trawl (mid-2006–2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [3]},
					CS_BOTTOM_TRAWL_2011_2015 : {key: "21", title:"CS Bottom Trawl (2011-2015)", tooltip:"Catch Shares Bottom Trawl (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [6]},
					CS_BOTTOM_TRAWL_2016_2017 : {key: "22", title:"CS Bottom Trawl (2016-2017)", tooltip:"Catch Shares Bottom Trawl (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [9]},
					AT_SEA_MID_TRAWL_CP_2002_2005 : {key: "23", title:"At-Sea Midwater Trawl CP (2002-2005)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2002–2005)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [12]},
					AT_SEA_MID_TRAWL_CP_2006_2010 : {key: "24", title:"At-Sea Midwater Trawl CP (2006-2010)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2006–2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [15]},
					AT_SEA_MID_TRAWL_CP_2011_2015 : {key: "25", title:"At-Sea Midwater Trawl CP (2011-2015)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [18]},
					AT_SEA_MID_TRAWL_CP_2016_2017 : {key: "26", title:"At-Sea Midwater Trawl CP (2011-2015)", tooltip:"At-Sea Midwater Trawl Catcher-Processor (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [21]},
					AT_SEA_MID_TRAWL_MS_2002_2005 : {key: "27", title:"At-Sea Midwater Trawl MS (2002-2005)", tooltip:"At-Sea Midwater Trawl Mothership (2002–2005)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [24]},
					AT_SEA_MID_TRAWL_MS_2006_2010 : {key: "28", title:"At-Sea Midwater Trawl MS (2006-2010)", tooltip:"At-Sea Midwater Trawl Mothership (2006–2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [27]},
					AT_SEA_MID_TRAWL_MS_2011_2015 : {key: "29", title:"At-Sea Midwater Trawl MS (2011-2015)", tooltip:"At-Sea Midwater Trawl Mothership (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [30]},
					AT_SEA_MID_TRAWL_MS_2016_2017 : {key: "30", title:"At-Sea Midwater Trawl MS (2016-2017)", tooltip:"At-Sea Midwater Trawl Mothership (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [33]},
					SHORESIDE_MID_TRAWL_HAKE_2011_2015 : {key: "31", title:"Shoreside Midwater Trawl Hake (2011-2015)", tooltip:"Shoreside Midwater Trawl for Hake (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [36]},
					SHORESIDE_MID_TRAWL_HAKE_2016_2017 : {key: "32", title:"Shoreside Midwater Trawl Hake (2016-2017)", tooltip:"Shoreside Midwater Trawl for Hake (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [39]},
					SHORESIDE_MID_TRAWL_ROCKFISH_2011_2015 : {key: "33", title:"Shoreside Midwater Trawl Rockfish (2011-2015)", tooltip:"Shoreside Midwater Trawl for Rockfish (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [42]},
					SHORESIDE_MID_TRAWL_ROCKFISH_2016_2017 : {key: "34", title:"Shoreside Midwater Trawl Rockfish (2016-2017)", tooltip:"Shoreside Midwater Trawl for Rockfish (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [45]},
					NON_CS_HOOK_LINE_2002_2010 : {key: "35", title:"Non-CS Hook & Line (2002-2010)", tooltip:"Non-Catch Shares Hook-and-Line (2002–2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [48]},
					NON_CS_HOOK_LINE_2011_2015 : {key: "36", title:"Non-CS Hook & Line (2011-2015)", tooltip:"Non-Catch Shares Hook-and-Line (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [51]},
					NON_CS_HOOK_LINE_2016_2017 : {key: "37", title:"Non-CS Hook & Line (2016-2017)", tooltip:"Non-Catch Shares Hook-and-Line (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [54]},
					CS_HOOK_LINE_2011_2017 : {key: "38", title:"CS Hook & Line (2011-2017)", tooltip:"Catch Shares Hook-and-Line (2011–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [57]},
					NON_CS_POT_2002_2010 : {key: "39", title:"Non-CS Pot (2002-2010)", tooltip:"Non-Catch Shares Pot (2002–2010)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [60]},
					NON_CS_POT_2011_2015 : {key: "40", title:"Non-CS Pot (2011-2015)", tooltip:"Non-Catch Shares Pot (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [63]},
					NON_CS_POT_2016_2017 : {key: "41", title:"Non-CS Pot (2016-2017)", tooltip:"Non-Catch Shares Pot (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [66]},
					CS_POT_2011_2015 : {key: "42", title:"CS Pot (2011-2015)", tooltip:"Catch Shares Pot (2011–2015)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [69]},
					CS_POT_2016_2017 : {key: "43", title:"CS Pot (2016-2017)", tooltip:"Catch Shares Pot (2016–2017)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/FishingEffort_2002_17_PacCoastGF/MapServer',mapServices: [72]}
					},
			},
	EFH : {key: "44", title:"Groundfish Essential Fish Habitat (EFH)",
			AMENDMENT_28 : {key: "45", title:"Amendment 28",
					EFH_CONS_AREA : {key: "46", title:"EFH Conservation Areas", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd28_FinalRule/FeatureServer',mapServices: [0]},
					EFH_700_FM : {key: "47", title:"EFH 700 fm bottom trawl closure", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd28_FinalRule/FeatureServer',mapServices: [1]},
					TRAWL_RCA_REMOVE : {key: "48", title:"Trawl RCA (removed)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd28_FinalRule/FeatureServer',mapServices: [3]},
					DECA : {key: "49", title:"Deep-sea Ecosystem Cons. Area", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd28_FinalRule/FeatureServer',mapServices: [2]},
					PFMC_FPA_ALT1H : {key: "50", title:"PFMC Final Preferred Alternative (Alt. 1h)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd28_FinalPrefAlt/FeatureServer',mapServices: [0]}
					},
			AMENDMENT_19 : {key: "51", title:"Amendment 19",
					HAPC_SEAGRASS : {key: "52", title:"HAPC-seagrass", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd19_FinalRule/FeatureServer',mapServices: [0]},
					HAPC_CANOPY_KELP : {key: "53", title:"HAPC-canopy kelp", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd19_FinalRule/FeatureServer',mapServices: [1]},
					HAPC_ESTUARY : {key: "54", title:"HAPC-estuary", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd19_FinalRule/FeatureServer',mapServices: [2]},
					HAPC_ROCKY_REEF : {key: "55", title:"HAPC-rocky reef", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd19_FinalRule/FeatureServer',mapServices: [3]},
					HAPC_AOI : {key: "56", title:"HAPC-area of interest", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd19_FinalRule/FeatureServer',mapServices: [4]},
					EFH_DESIGNATED_AREA : {key: "57", title:"EFH Designated Area", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/EFH_GF_Amd19_FinalRule/FeatureServer',mapServices: [5]}
					},
			SPECIES_DISTRIBUTION : {key: "58", title:"Species Distribution",
					CORAL_SPONGE_OBS : {key: "59", title:"Coral and Sponge Observations", url : 'https://tiles.arcgis.com/tiles/C8EMgrsFcRFL6LrL/arcgis/rest/services/DSCRTP/MapServer',mapServices: []}
					}
			},
	SPATIAL_REFERENCES : {key: "60", title:"Spatial References",
			BATHYMETRIC_CONTOURS : {key: "61", title:"Bathymetric Contours", url : 'https://gis.ngdc.noaa.gov/arcgis/rest/services/web_mercator/gebco_2014_contours/MapServer',mapServices: []},
			PFMC_LANDMARKS : {key: "62", title:"PFMC Landmarks", url:'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/PFMC_Management_Landmarks_and_Areas/FeatureServer',mapServices: [0]},
			INPFC_AREAS : {key: "63", title:"INPFC Areas", url:'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/PFMC_Management_Landmarks_and_Areas/FeatureServer',mapServices: [1]}
			},
			HABITAT_MAP : {key: "64", title:"Habitat Map",
					SGH_IND : {key: "65", title:"Surficial Geologic Habitat - Induration (hard, mixed, soft)", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/USWestCoast_SeafloorInduration_v4_0/MapServer',mapServices: [0]},
					SGH_QUALITY : {key: "66", title:"Surficial Geologic Habitat - Data Quality", url : 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/FRAM/USWestCoast_SeafloorInduration_v4_0/MapServer',mapServices: [2]}
					},
			REGULATORY_BOUNDARIES : {key: "67", title:"Regulatory Boundaries",
					RCA_LINES : {key: "68", title:"RCA Lines (2019-2020)", url:'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/West_Coast_Rockfish_Conservation_Areas/FeatureServer',mapServices: [0]},
					TRAWL_RCA_POLYGONS : {key: "69", title:"Trawl RCA Polygons (2019-2020)", url:'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/West_Coast_Rockfish_Conservation_Areas/FeatureServer',mapServices: [1]},
					MARINE_PROTECTED_AREAS : {key: "70", title:"Marine Protected Areas", url : 'https://services2.arcgis.com/C8EMgrsFcRFL6LrL/arcgis/rest/services/MPAI_2020_WMS/FeatureServer',mapServices: [0]},
					EEZ : {key: "71", title:"Economic Exclusion Zone (EEZ)", url : 'https://maritimeboundaries.noaa.gov/arcgis/rest/services/MaritimeBoundaries/US_Maritime_Limits_Boundaries/MapServer',mapServices: [3]},
					SUBMERGED_LANDS_ACT_BOUNDARY : {key: "72", title:"Submerged Lands Act Boundary", url : 'https://gis.boem.gov/arcgis/rest/services/BOEM_BSEE/MMC_Layers/MapServer',mapServices: [8]}
					}
			}
;